[package]
name = "mixlib"
version = "0.4.0"
edition = "2024"
readme = "Readme.md"
license = "MIT"
repository = "https://github.com/jhunterkohler/mix/tree/master/mixlib"
description = "MIX architecture utilities"

[dev-dependencies]
