[package]
name = "mixlib"
version = "0.2.0"
edition = "2021"
readme = "Readme.md"
license = "MIT"
repository = "https://github.com/jhunterkohler/mix/tree/master/mixlib"
description = "MIX architecture utilities"

[dependencies]
regex = "1.11.1"
